name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 根据你的主分支名设置触发条件...

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t loveu5522/local-media-scraper:latest .

    - name: Push Docker image
      run: docker push loveu5522/local-media-scraper:latest
