name: 构建并推送 Docker 镜像

# 当推送到 main 分支时触发构建
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: 检出代码
      uses: actions/checkout@v2

    # 设置 Docker Buildx
    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v1

    # 登录到 Docker Hub
    - name: 登录到 Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # 确定新版本号
    - name: 确定新版本号
      id: determine_version
      run: |
        version=$(date +"%Y-%m-%d-%H%M%S")
        echo "::set-output name=NEW_VERSION::$version"

    # 构建 Docker 镜像
    - name: 构建 Docker 镜像
      run: docker build -t loveu5522/local-media-scraper:${{ steps.determine_version.outputs.NEW_VERSION }} .

    # 标记 Docker 镜像
    - name: 标记 Docker 镜像
      run: docker tag loveu5522/local-media-scraper:${{ steps.determine_version.outputs.NEW_VERSION }} loveu5522/local-media-scraper:latest

    # 推送 Docker 镜像
    - name: 推送 Docker 镜像
      run: docker push loveu5522/local-media-scraper:${{ steps.determine_version.outputs.NEW_VERSION }} && docker push loveu5522/local-media-scraper:latest
